// <auto-generated />
using System;
using CMS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMS.DAL.Migrations
{
    [DbContext(typeof(CourseServiceDbContext))]
    [Migration("20190420204237_initial-create")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMS.DAL.DbEntities.CourseInformation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseDescription");

                    b.Property<string>("CourseTitle");

                    b.Property<DateTime>("CreationTime");

                    b.Property<bool>("Deleted");

                    b.Property<int?>("FKPreviousVersionID");

                    b.Property<int>("FKTeacherID");

                    b.Property<DateTime?>("LastUpdateTime");

                    b.HasKey("ID");

                    b.ToTable("CourseInformations");
                });

            modelBuilder.Entity("CMS.DAL.DbEntities.StudentCourseJunction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime");

                    b.Property<int>("FKCourseID");

                    b.Property<int>("FKStudentID");

                    b.Property<DateTime?>("LastUpdateTime");

                    b.HasKey("ID");

                    b.HasIndex("FKStudentID", "FKCourseID")
                        .IsUnique();

                    b.ToTable("StudentCourseJunctions");
                });

            modelBuilder.Entity("CMS.DAL.DbEntities.StudentCourseScore", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime");

                    b.Property<bool>("Deleted");

                    b.Property<int>("FKCourseID");

                    b.Property<int?>("FKPreviousVersionID");

                    b.Property<int>("FKStudentID");

                    b.Property<DateTime?>("LastUpdateTime");

                    b.Property<double>("Score");

                    b.HasKey("ID");

                    b.HasIndex("FKStudentID", "FKCourseID", "Deleted")
                        .IsUnique();

                    b.ToTable("StudentCourseScores");
                });
#pragma warning restore 612, 618
        }
    }
}
